-- ============================================
-- COMPLETE TEST DATA FOR ORDERS TABLE
-- Dashboard Analytics Testing
-- ============================================
-- STEP 1: Get your user_id (Run this first and copy the result)
-- SELECT id FROM users LIMIT 1;
-- STEP 2: Replace 'YOUR_USER_ID_HERE' below with the actual user_id
-- ============================================
-- TEST ORDERS FOR OCTOBER 2024
-- ============================================
-- Order 1: October 5, 2024 - ₹500
INSERT INTO orders (
        user_id,
        order_number,
        status,
        payment_status,
        item_total,
        delivery_charge,
        discount_amount,
        cgst,
        sgst,
        total_amount,
        delivery_address_id,
        delivery_address_text,
        notes,
        is_knife,
        is_candle,
        is_text_on_card,
        text_on_card,
        delivery_timing,
        delivery_date,
        delivery_time_slot,
        contact_name,
        contact_number,
        contact_alternate_number,
        is_coupon,
        coupon_id,
        coupon_code,
        estimated_time_delivery,
        delivery_zone,
        delivery_person_name,
        delivery_person_contact,
        payment_method,
        payment_transaction_id,
        latest_payment_id,
        preparation_time,
        cooking_started_at,
        ready_at,
        picked_up_at,
        delivered_at,
        customer_rating,
        customer_feedback,
        created_at
    )
VALUES (
        'YOUR_USER_ID_HERE',
        'TEST-2024-10-001',
        'delivered',
        'paid',
        450.00,
        50.00,
        0.00,
        0.00,
        0.00,
        500.00,
        NULL,
        '123 Test Street, Test City, 600001',
        NULL,
        false,
        false,
        false,
        NULL,
        'immediate',
        '2024-10-05',
        NULL,
        'Rajesh Kumar',
        '9876543210',
        NULL,
        false,
        NULL,
        NULL,
        '45 mins',
        'Zone A',
        NULL,
        NULL,
        'online',
        'TXN-OCT-001',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '2024-10-05 12:30:00',
        5,
        'Great service!',
        '2024-10-05 10:30:00'
    );
-- Order 2: October 7, 2024 - ₹850
INSERT INTO orders (
        user_id,
        order_number,
        status,
        payment_status,
        item_total,
        delivery_charge,
        discount_amount,
        cgst,
        sgst,
        total_amount,
        delivery_address_id,
        delivery_address_text,
        notes,
        is_knife,
        is_candle,
        is_text_on_card,
        text_on_card,
        delivery_timing,
        delivery_date,
        delivery_time_slot,
        contact_name,
        contact_number,
        contact_alternate_number,
        is_coupon,
        coupon_id,
        coupon_code,
        estimated_time_delivery,
        delivery_zone,
        delivery_person_name,
        delivery_person_contact,
        payment_method,
        payment_transaction_id,
        latest_payment_id,
        preparation_time,
        cooking_started_at,
        ready_at,
        picked_up_at,
        delivered_at,
        customer_rating,
        customer_feedback,
        created_at
    )
VALUES (
        'YOUR_USER_ID_HERE',
        'TEST-2024-10-002',
        'delivered',
        'paid',
        800.00,
        50.00,
        0.00,
        0.00,
        0.00,
        850.00,
        NULL,
        '456 Main Road, Test Town, 600002',
        'Please ring doorbell',
        false,
        false,
        false,
        NULL,
        'schedule',
        '2024-10-07',
        '18:00-20:00',
        'Priya Sharma',
        '9876543211',
        '9876543299',
        false,
        NULL,
        NULL,
        '60 mins',
        'Zone B',
        NULL,
        NULL,
        'upi',
        'TXN-OCT-002',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '2024-10-07 19:15:00',
        4,
        'Good quality',
        '2024-10-07 15:20:00'
    );
-- Order 3: October 9, 2024 - ₹1,371.60
INSERT INTO orders (
        user_id,
        order_number,
        status,
        payment_status,
        item_total,
        delivery_charge,
        discount_amount,
        cgst,
        sgst,
        total_amount,
        delivery_address_id,
        delivery_address_text,
        notes,
        is_knife,
        is_candle,
        is_text_on_card,
        text_on_card,
        delivery_timing,
        delivery_date,
        delivery_time_slot,
        contact_name,
        contact_number,
        contact_alternate_number,
        is_coupon,
        coupon_id,
        coupon_code,
        estimated_time_delivery,
        delivery_zone,
        delivery_person_name,
        delivery_person_contact,
        payment_method,
        payment_transaction_id,
        latest_payment_id,
        preparation_time,
        cooking_started_at,
        ready_at,
        picked_up_at,
        delivered_at,
        customer_rating,
        customer_feedback,
        created_at
    )
VALUES (
        'YOUR_USER_ID_HERE',
        'TEST-2024-10-003',
        'delivered',
        'paid',
        1250.00,
        121.60,
        0.00,
        0.00,
        0.00,
        1371.60,
        NULL,
        '789 Park Avenue, Test City, 600003',
        'Birthday cake - handle with care',
        true,
        true,
        true,
        'Happy Birthday!',
        'schedule',
        '2024-10-09',
        '14:00-16:00',
        'Amit Patel',
        '9876543212',
        NULL,
        false,
        NULL,
        NULL,
        '90 mins',
        'Zone A',
        NULL,
        NULL,
        'online',
        'TXN-OCT-003',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '2024-10-09 15:30:00',
        5,
        'Perfect delivery!',
        '2024-10-09 12:00:00'
    );
-- Order 4: October 10, 2024 - ₹750
INSERT INTO orders (
        user_id,
        order_number,
        status,
        payment_status,
        item_total,
        delivery_charge,
        discount_amount,
        cgst,
        sgst,
        total_amount,
        delivery_address_id,
        delivery_address_text,
        notes,
        is_knife,
        is_candle,
        is_text_on_card,
        text_on_card,
        delivery_timing,
        delivery_date,
        delivery_time_slot,
        contact_name,
        contact_number,
        contact_alternate_number,
        is_coupon,
        coupon_id,
        coupon_code,
        estimated_time_delivery,
        delivery_zone,
        delivery_person_name,
        delivery_person_contact,
        payment_method,
        payment_transaction_id,
        latest_payment_id,
        preparation_time,
        cooking_started_at,
        ready_at,
        picked_up_at,
        delivered_at,
        customer_rating,
        customer_feedback,
        created_at
    )
VALUES (
        'YOUR_USER_ID_HERE',
        'TEST-2024-10-004',
        'delivered',
        'paid',
        700.00,
        50.00,
        0.00,
        0.00,
        0.00,
        750.00,
        NULL,
        '321 Lake View, Test Area, 600004',
        NULL,
        false,
        false,
        false,
        NULL,
        'immediate',
        '2024-10-10',
        NULL,
        'Sneha Reddy',
        '9876543213',
        NULL,
        false,
        NULL,
        NULL,
        '45 mins',
        'Zone C',
        NULL,
        NULL,
        'cod',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '2024-10-10 18:20:00',
        4,
        NULL,
        '2024-10-10 16:45:00'
    );
-- Order 5: October 12, 2024 - ₹2,000
INSERT INTO orders (
        user_id,
        order_number,
        status,
        payment_status,
        item_total,
        delivery_charge,
        discount_amount,
        cgst,
        sgst,
        total_amount,
        delivery_address_id,
        delivery_address_text,
        notes,
        is_knife,
        is_candle,
        is_text_on_card,
        text_on_card,
        delivery_timing,
        delivery_date,
        delivery_time_slot,
        contact_name,
        contact_number,
        contact_alternate_number,
        is_coupon,
        coupon_id,
        coupon_code,
        estimated_time_delivery,
        delivery_zone,
        delivery_person_name,
        delivery_person_contact,
        payment_method,
        payment_transaction_id,
        latest_payment_id,
        preparation_time,
        cooking_started_at,
        ready_at,
        picked_up_at,
        delivered_at,
        customer_rating,
        customer_feedback,
        created_at
    )
VALUES (
        'YOUR_USER_ID_HERE',
        'TEST-2024-10-005',
        'delivered',
        'paid',
        1850.00,
        150.00,
        0.00,
        0.00,
        0.00,
        2000.00,
        NULL,
        '567 Beach Road, Test Beach, 600005',
        'Office party order',
        false,
        false,
        false,
        NULL,
        'schedule',
        '2024-10-12',
        '12:00-14:00',
        'Vikram Singh',
        '9876543214',
        '9876543288',
        false,
        NULL,
        NULL,
        '120 mins',
        'Zone B',
        NULL,
        NULL,
        'online',
        'TXN-OCT-005',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '2024-10-12 13:45:00',
        5,
        'Excellent for party!',
        '2024-10-12 09:30:00'
    );
-- Order 6: October 14, 2024 - ₹1,100
INSERT INTO orders (
        user_id,
        order_number,
        status,
        payment_status,
        item_total,
        delivery_charge,
        discount_amount,
        cgst,
        sgst,
        total_amount,
        delivery_address_id,
        delivery_address_text,
        notes,
        is_knife,
        is_candle,
        is_text_on_card,
        text_on_card,
        delivery_timing,
        delivery_date,
        delivery_time_slot,
        contact_name,
        contact_number,
        contact_alternate_number,
        is_coupon,
        coupon_id,
        coupon_code,
        estimated_time_delivery,
        delivery_zone,
        delivery_person_name,
        delivery_person_contact,
        payment_method,
        payment_transaction_id,
        latest_payment_id,
        preparation_time,
        cooking_started_at,
        ready_at,
        picked_up_at,
        delivered_at,
        customer_rating,
        customer_feedback,
        created_at
    )
VALUES (
        'YOUR_USER_ID_HERE',
        'TEST-2024-10-006',
        'delivered',
        'paid',
        1000.00,
        100.00,
        0.00,
        0.00,
        0.00,
        1100.00,
        NULL,
        '890 Hill Street, Test Hills, 600006',
        NULL,
        false,
        false,
        false,
        NULL,
        'immediate',
        '2024-10-14',
        NULL,
        'Meera Nair',
        '9876543215',
        NULL,
        false,
        NULL,
        NULL,
        '60 mins',
        'Zone A',
        NULL,
        NULL,
        'upi',
        'TXN-OCT-006',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '2024-10-14 17:00:00',
        4,
        'Tasty!',
        '2024-10-14 14:30:00'
    );
-- Order 7: October 15, 2024 - ₹1,200
INSERT INTO orders (
        user_id,
        order_number,
        status,
        payment_status,
        item_total,
        delivery_charge,
        discount_amount,
        cgst,
        sgst,
        total_amount,
        delivery_address_id,
        delivery_address_text,
        notes,
        is_knife,
        is_candle,
        is_text_on_card,
        text_on_card,
        delivery_timing,
        delivery_date,
        delivery_time_slot,
        contact_name,
        contact_number,
        contact_alternate_number,
        is_coupon,
        coupon_id,
        coupon_code,
        estimated_time_delivery,
        delivery_zone,
        delivery_person_name,
        delivery_person_contact,
        payment_method,
        payment_transaction_id,
        latest_payment_id,
        preparation_time,
        cooking_started_at,
        ready_at,
        picked_up_at,
        delivered_at,
        customer_rating,
        customer_feedback,
        created_at
    )
VALUES (
        'YOUR_USER_ID_HERE',
        'TEST-2024-10-007',
        'preparing',
        'paid',
        1100.00,
        100.00,
        0.00,
        0.00,
        0.00,
        1200.00,
        NULL,
        '234 Garden Lane, Test Garden, 600007',
        'Anniversary surprise',
        true,
        true,
        true,
        'Happy Anniversary!',
        'schedule',
        '2024-10-15',
        '20:00-22:00',
        'Arjun Desai',
        '9876543216',
        NULL,
        false,
        NULL,
        NULL,
        '75 mins',
        'Zone C',
        NULL,
        NULL,
        'online',
        'TXN-OCT-007',
        NULL,
        45,
        '2024-10-15 18:30:00',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '2024-10-15 17:00:00'
    );
-- Order 8: October 16, 2024 - ₹650
INSERT INTO orders (
        user_id,
        order_number,
        status,
        payment_status,
        item_total,
        delivery_charge,
        discount_amount,
        cgst,
        sgst,
        total_amount,
        delivery_address_id,
        delivery_address_text,
        notes,
        is_knife,
        is_candle,
        is_text_on_card,
        text_on_card,
        delivery_timing,
        delivery_date,
        delivery_time_slot,
        contact_name,
        contact_number,
        contact_alternate_number,
        is_coupon,
        coupon_id,
        coupon_code,
        estimated_time_delivery,
        delivery_zone,
        delivery_person_name,
        delivery_person_contact,
        payment_method,
        payment_transaction_id,
        latest_payment_id,
        preparation_time,
        cooking_started_at,
        ready_at,
        picked_up_at,
        delivered_at,
        customer_rating,
        customer_feedback,
        created_at
    )
VALUES (
        'YOUR_USER_ID_HERE',
        'TEST-2024-10-008',
        'delivered',
        'paid',
        600.00,
        50.00,
        0.00,
        0.00,
        0.00,
        650.00,
        NULL,
        '678 River Side, Test River, 600008',
        NULL,
        false,
        false,
        false,
        NULL,
        'immediate',
        '2024-10-16',
        NULL,
        'Kavya Menon',
        '9876543217',
        NULL,
        false,
        NULL,
        NULL,
        '40 mins',
        'Zone B',
        NULL,
        NULL,
        'cod',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '2024-10-16 13:15:00',
        5,
        'Quick delivery',
        '2024-10-16 11:30:00'
    );
-- ============================================
-- VERIFICATION QUERY
-- ============================================
-- Run this to verify all orders were inserted correctly
SELECT order_number,
    contact_name,
    total_amount,
    payment_status,
    status,
    TO_CHAR(created_at::timestamp, 'YYYY-MM-DD HH24:MI:SS') as order_date
FROM orders
WHERE order_number LIKE 'TEST-2024-10-%'
ORDER BY created_at;
-- ============================================
-- SUMMARY STATISTICS
-- ============================================
-- Total orders and revenue
SELECT COUNT(*) as total_orders,
    SUM(total_amount) as total_revenue,
    AVG(total_amount) as average_order_value
FROM orders
WHERE order_number LIKE 'TEST-2024-10-%'
    AND payment_status = 'paid';
-- Daily breakdown
SELECT DATE(created_at) as order_date,
    COUNT(*) as orders_count,
    SUM(total_amount) as daily_revenue
FROM orders
WHERE order_number LIKE 'TEST-2024-10-%'
    AND payment_status = 'paid'
GROUP BY DATE(created_at)
ORDER BY order_date;
-- ============================================
-- CLEANUP (Run this when you're done testing)
-- ============================================
-- Uncomment and run this to delete all test orders
