-- ============================================
-- TEST DATA BASED ON YOUR ACTUAL ORDER STRUCTURE
-- Multiple Orders with Different Dates & Prices
-- ============================================
-- Replace this with your actual user_id
-- User ID: 60ecf424-c510-4498-8dcc-72fa273116ce
-- Order 1: October 5, 2024 - ₹500
INSERT INTO orders (
        user_id,
        order_number,
        status,
        payment_status,
        item_total,
        delivery_charge,
        discount_amount,
        cgst,
        sgst,
        total_amount,
        delivery_address_id,
        notes,
        is_knife,
        is_candle,
        is_text_on_card,
        text_on_card,
        delivery_timing,
        delivery_date,
        delivery_time_slot,
        contact_name,
        contact_number,
        contact_alternate_number,
        is_coupon,
        coupon_id,
        coupon_code,
        estimated_time_delivery,
        delivery_zone,
        payment_method,
        payment_transaction_id,
        preparation_time,
        cooking_started_at,
        ready_at,
        picked_up_at,
        delivered_at,
        customer_rating,
        customer_feedback,
        created_at,
        delivery_person_name,
        delivery_person_contact,
        latest_payment_id
    )
VALUES (
        '60ecf424-c510-4498-8dcc-72fa273116ce',
        'TEST-2024-10-001',
        'delivered',
        'paid',
        400.00,
        50.00,
        0.00,
        25.00,
        25.00,
        500.00,
        'f517f5a3-2fd0-4ea6-aef2-b573b1cb6281',
        null,
        false,
        false,
        false,
        null,
        'same_day',
        null,
        null,
        'Ashwin C S',
        '8248669086',
        null,
        false,
        null,
        null,
        '2024-10-05 18:00:00+00',
        null,
        'online',
        'pay_TEST001',
        null,
        '2024-10-05 11:00:00+00',
        null,
        '2024-10-05 11:30:00+00',
        '2024-10-05 12:00:00+00',
        5,
        'Great service!',
        '2024-10-05 10:30:00+00',
        'Delivery Person 1',
        '9876543210',
        null
    );
-- Order 2: October 7, 2024 - ₹850
INSERT INTO orders (
        user_id,
        order_number,
        status,
        payment_status,
        item_total,
        delivery_charge,
        discount_amount,
        cgst,
        sgst,
        total_amount,
        delivery_address_id,
        notes,
        is_knife,
        is_candle,
        is_text_on_card,
        text_on_card,
        delivery_timing,
        delivery_date,
        delivery_time_slot,
        contact_name,
        contact_number,
        contact_alternate_number,
        is_coupon,
        coupon_id,
        coupon_code,
        estimated_time_delivery,
        delivery_zone,
        payment_method,
        payment_transaction_id,
        preparation_time,
        cooking_started_at,
        ready_at,
        picked_up_at,
        delivered_at,
        customer_rating,
        customer_feedback,
        created_at,
        delivery_person_name,
        delivery_person_contact,
        latest_payment_id
    )
VALUES (
        '60ecf424-c510-4498-8dcc-72fa273116ce',
        'TEST-2024-10-002',
        'delivered',
        'paid',
        700.00,
        75.00,
        0.00,
        37.50,
        37.50,
        850.00,
        'f517f5a3-2fd0-4ea6-aef2-b573b1cb6281',
        'Please deliver by evening',
        false,
        false,
        false,
        null,
        'same_day',
        null,
        null,
        'Ashwin C S',
        '8248669086',
        null,
        false,
        null,
        null,
        '2024-10-07 19:00:00+00',
        null,
        'online',
        'pay_TEST002',
        null,
        '2024-10-07 16:00:00+00',
        null,
        '2024-10-07 16:45:00+00',
        '2024-10-07 18:30:00+00',
        4,
        'Good quality',
        '2024-10-07 15:20:00+00',
        'Delivery Person 2',
        '9876543211',
        null
    );
-- Order 3: October 9, 2024 - ₹1,371.60 (Your actual order amount)
INSERT INTO orders (
        user_id,
        order_number,
        status,
        payment_status,
        item_total,
        delivery_charge,
        discount_amount,
        cgst,
        sgst,
        total_amount,
        delivery_address_id,
        notes,
        is_knife,
        is_candle,
        is_text_on_card,
        text_on_card,
        delivery_timing,
        delivery_date,
        delivery_time_slot,
        contact_name,
        contact_number,
        contact_alternate_number,
        is_coupon,
        coupon_id,
        coupon_code,
        estimated_time_delivery,
        delivery_zone,
        payment_method,
        payment_transaction_id,
        preparation_time,
        cooking_started_at,
        ready_at,
        picked_up_at,
        delivered_at,
        customer_rating,
        customer_feedback,
        created_at,
        delivery_person_name,
        delivery_person_contact,
        latest_payment_id
    )
VALUES (
        '60ecf424-c510-4498-8dcc-72fa273116ce',
        'TEST-2024-10-003',
        'delivered',
        'paid',
        1070.00,
        109.00,
        0.00,
        96.30,
        96.30,
        1371.60,
        'f517f5a3-2fd0-4ea6-aef2-b573b1cb6281',
        'Birthday cake - handle with care',
        true,
        true,
        true,
        'Happy Birthday!',
        'same_day',
        null,
        null,
        'Ashwin C S',
        '8248669086',
        null,
        false,
        null,
        null,
        '2024-10-09 18:00:00+00',
        null,
        'online',
        'pay_TEST003',
        null,
        '2024-10-09 13:30:00+00',
        null,
        '2024-10-09 14:00:00+00',
        '2024-10-09 17:00:00+00',
        5,
        'Perfect delivery!',
        '2024-10-09 12:00:00+00',
        'Delivery Person 3',
        '9876543212',
        null
    );
-- Order 4: October 10, 2024 - ₹750
INSERT INTO orders (
        user_id,
        order_number,
        status,
        payment_status,
        item_total,
        delivery_charge,
        discount_amount,
        cgst,
        sgst,
        total_amount,
        delivery_address_id,
        notes,
        is_knife,
        is_candle,
        is_text_on_card,
        text_on_card,
        delivery_timing,
        delivery_date,
        delivery_time_slot,
        contact_name,
        contact_number,
        contact_alternate_number,
        is_coupon,
        coupon_id,
        coupon_code,
        estimated_time_delivery,
        delivery_zone,
        payment_method,
        payment_transaction_id,
        preparation_time,
        cooking_started_at,
        ready_at,
        picked_up_at,
        delivered_at,
        customer_rating,
        customer_feedback,
        created_at,
        delivery_person_name,
        delivery_person_contact,
        latest_payment_id
    )
VALUES (
        '60ecf424-c510-4498-8dcc-72fa273116ce',
        'TEST-2024-10-004',
        'delivered',
        'paid',
        600.00,
        75.00,
        0.00,
        37.50,
        37.50,
        750.00,
        'f517f5a3-2fd0-4ea6-aef2-b573b1cb6281',
        null,
        false,
        false,
        false,
        null,
        'same_day',
        null,
        null,
        'Ashwin C S',
        '8248669086',
        null,
        false,
        null,
        null,
        '2024-10-10 20:00:00+00',
        null,
        'online',
        'pay_TEST004',
        null,
        '2024-10-10 17:15:00+00',
        null,
        '2024-10-10 17:45:00+00',
        '2024-10-10 19:30:00+00',
        4,
        null,
        '2024-10-10 16:45:00+00',
        'Delivery Person 1',
        '9876543210',
        null
    );
-- Order 5: October 12, 2024 - ₹2,000
INSERT INTO orders (
        user_id,
        order_number,
        status,
        payment_status,
        item_total,
        delivery_charge,
        discount_amount,
        cgst,
        sgst,
        total_amount,
        delivery_address_id,
        notes,
        is_knife,
        is_candle,
        is_text_on_card,
        text_on_card,
        delivery_timing,
        delivery_date,
        delivery_time_slot,
        contact_name,
        contact_number,
        contact_alternate_number,
        is_coupon,
        coupon_id,
        coupon_code,
        estimated_time_delivery,
        delivery_zone,
        payment_method,
        payment_transaction_id,
        preparation_time,
        cooking_started_at,
        ready_at,
        picked_up_at,
        delivered_at,
        customer_rating,
        customer_feedback,
        created_at,
        delivery_person_name,
        delivery_person_contact,
        latest_payment_id
    )
VALUES (
        '60ecf424-c510-4498-8dcc-72fa273116ce',
        'TEST-2024-10-005',
        'delivered',
        'paid',
        1600.00,
        175.00,
        0.00,
        112.50,
        112.50,
        2000.00,
        'f517f5a3-2fd0-4ea6-aef2-b573b1cb6281',
        'Office party order - Large quantity',
        false,
        false,
        false,
        null,
        'same_day',
        null,
        null,
        'Ashwin C S',
        '8248669086',
        null,
        false,
        null,
        null,
        '2024-10-12 14:00:00+00',
        null,
        'online',
        'pay_TEST005',
        null,
        '2024-10-12 10:00:00+00',
        null,
        '2024-10-12 11:30:00+00',
        '2024-10-12 13:45:00+00',
        5,
        'Excellent for party!',
        '2024-10-12 09:30:00+00',
        'Delivery Person 2',
        '9876543211',
        null
    );
-- Order 6: October 14, 2024 - ₹1,100
INSERT INTO orders (
        user_id,
        order_number,
        status,
        payment_status,
        item_total,
        delivery_charge,
        discount_amount,
        cgst,
        sgst,
        total_amount,
        delivery_address_id,
        notes,
        is_knife,
        is_candle,
        is_text_on_card,
        text_on_card,
        delivery_timing,
        delivery_date,
        delivery_time_slot,
        contact_name,
        contact_number,
        contact_alternate_number,
        is_coupon,
        coupon_id,
        coupon_code,
        estimated_time_delivery,
        delivery_zone,
        payment_method,
        payment_transaction_id,
        preparation_time,
        cooking_started_at,
        ready_at,
        picked_up_at,
        delivered_at,
        customer_rating,
        customer_feedback,
        created_at,
        delivery_person_name,
        delivery_person_contact,
        latest_payment_id
    )
VALUES (
        '60ecf424-c510-4498-8dcc-72fa273116ce',
        'TEST-2024-10-006',
        'delivered',
        'paid',
        900.00,
        100.00,
        0.00,
        50.00,
        50.00,
        1100.00,
        'f517f5a3-2fd0-4ea6-aef2-b573b1cb6281',
        null,
        false,
        false,
        false,
        null,
        'same_day',
        null,
        null,
        'Ashwin C S',
        '8248669086',
        null,
        false,
        null,
        null,
        '2024-10-14 17:00:00+00',
        null,
        'online',
        'pay_TEST006',
        null,
        '2024-10-14 15:00:00+00',
        null,
        '2024-10-14 15:30:00+00',
        '2024-10-14 16:45:00+00',
        4,
        'Tasty!',
        '2024-10-14 14:30:00+00',
        'Delivery Person 3',
        '9876543212',
        null
    );
-- Order 7: October 15, 2024 - ₹1,200
INSERT INTO orders (
        user_id,
        order_number,
        status,
        payment_status,
        item_total,
        delivery_charge,
        discount_amount,
        cgst,
        sgst,
        total_amount,
        delivery_address_id,
        notes,
        is_knife,
        is_candle,
        is_text_on_card,
        text_on_card,
        delivery_timing,
        delivery_date,
        delivery_time_slot,
        contact_name,
        contact_number,
        contact_alternate_number,
        is_coupon,
        coupon_id,
        coupon_code,
        estimated_time_delivery,
        delivery_zone,
        payment_method,
        payment_transaction_id,
        preparation_time,
        cooking_started_at,
        ready_at,
        picked_up_at,
        delivered_at,
        customer_rating,
        customer_feedback,
        created_at,
        delivery_person_name,
        delivery_person_contact,
        latest_payment_id
    )
VALUES (
        '60ecf424-c510-4498-8dcc-72fa273116ce',
        'TEST-2024-10-007',
        'preparing',
        'paid',
        1000.00,
        100.00,
        0.00,
        50.00,
        50.00,
        1200.00,
        'f517f5a3-2fd0-4ea6-aef2-b573b1cb6281',
        'Anniversary surprise',
        true,
        true,
        true,
        'Happy Anniversary!',
        'same_day',
        null,
        null,
        'Ashwin C S',
        '8248669086',
        null,
        false,
        null,
        null,
        '2024-10-15 21:00:00+00',
        null,
        'online',
        'pay_TEST007',
        45,
        '2024-10-15 18:00:00+00',
        null,
        null,
        null,
        null,
        null,
        '2024-10-15 17:00:00+00',
        null,
        null,
        null
    );
-- Order 8: October 16, 2024 - ₹650
INSERT INTO orders (
        user_id,
        order_number,
        status,
        payment_status,
        item_total,
        delivery_charge,
        discount_amount,
        cgst,
        sgst,
        total_amount,
        delivery_address_id,
        notes,
        is_knife,
        is_candle,
        is_text_on_card,
        text_on_card,
        delivery_timing,
        delivery_date,
        delivery_time_slot,
        contact_name,
        contact_number,
        contact_alternate_number,
        is_coupon,
        coupon_id,
        coupon_code,
        estimated_time_delivery,
        delivery_zone,
        payment_method,
        payment_transaction_id,
        preparation_time,
        cooking_started_at,
        ready_at,
        picked_up_at,
        delivered_at,
        customer_rating,
        customer_feedback,
        created_at,
        delivery_person_name,
        delivery_person_contact,
        latest_payment_id
    )
VALUES (
        '60ecf424-c510-4498-8dcc-72fa273116ce',
        'TEST-2024-10-008',
        'delivered',
        'paid',
        525.00,
        60.00,
        0.00,
        32.50,
        32.50,
        650.00,
        'f517f5a3-2fd0-4ea6-aef2-b573b1cb6281',
        null,
        false,
        false,
        false,
        null,
        'same_day',
        null,
        null,
        'Ashwin C S',
        '8248669086',
        null,
        false,
        null,
        null,
        '2024-10-16 14:00:00+00',
        null,
        'online',
        'pay_TEST008',
        null,
        '2024-10-16 12:00:00+00',
        null,
        '2024-10-16 12:30:00+00',
        '2024-10-16 13:45:00+00',
        5,
        'Quick delivery',
        '2024-10-16 11:30:00+00',
        'Delivery Person 1',
        '9876543210',
        null
    );
-- ============================================
-- VERIFICATION QUERY
-- ============================================
SELECT order_number,
    contact_name,
    total_amount,
    payment_status,
    status,
    created_at
FROM orders
WHERE order_number LIKE 'TEST-2024-10-%'
ORDER BY created_at;
-- ============================================
-- SUMMARY STATISTICS
-- ============================================
SELECT COUNT(*) as total_orders,
    SUM(total_amount) as total_revenue,
    ROUND(AVG(total_amount)::numeric, 2) as average_order_value
FROM orders
WHERE order_number LIKE 'TEST-2024-10-%'
    AND payment_status = 'paid';
-- Daily breakdown
SELECT DATE(created_at) as order_date,
    COUNT(*) as orders_count,
    SUM(total_amount) as daily_revenue
FROM orders
WHERE order_number LIKE 'TEST-2024-10-%'
    AND payment_status = 'paid'
GROUP BY DATE(created_at)
ORDER BY order_date;
-- ============================================
-- CLEANUP (Uncomment to delete test data)
-- ============================================
-- DELETE FROM orders WHERE order_number LIKE 'TEST-2024-10-%';