-- Sample Products Data for Duchess Pastries
-- This script inserts the sample products from the admin interface into the database
-- First, let's get the category IDs we need
DO $$
DECLARE cakes_id UUID;
cupcakes_id UUID;
cookies_id UUID;
pastries_id UUID;
breads_id UUID;
donuts_id UUID;
brownies_id UUID;
BEGIN -- Get category IDs
SELECT id INTO cakes_id
FROM categories
WHERE name = 'Cakes';
SELECT id INTO cupcakes_id
FROM categories
WHERE name = 'Cupcakes';
SELECT id INTO cookies_id
FROM categories
WHERE name = 'Cookies';
SELECT id INTO pastries_id
FROM categories
WHERE name = 'Pastries';
SELECT id INTO breads_id
FROM categories
WHERE name = 'Breads';
SELECT id INTO donuts_id
FROM categories
WHERE name = 'Donuts';
SELECT id INTO brownies_id
FROM categories
WHERE name = 'Brownies';
-- Insert Chocolate Cake
INSERT INTO products (
        name,
        short_description,
        long_description,
        category_id,
        is_veg,
        has_offer,
        offer_percentage,
        offer_up_to_price,
        banner_image,
        additional_images,
        selling_type,
        weight_options,
        piece_options,
        calories,
        net_weight,
        protein,
        fats,
        carbs,
        sugars,
        fiber,
        sodium,
        delivery_option,
        add_text_on_cake,
        add_candles,
        add_knife,
        add_message_card,
        highlights,
        ingredients,
        is_active
    )
VALUES (
        'Chocolate Cake',
        'Rich chocolate cake with creamy ganache frosting.',
        'A rich and moist chocolate cake, perfect for any occasion. Made with premium cocoa and topped with a smooth chocolate ganache.',
        cakes_id,
        true,
        false,
        NULL,
        0,
        '/decadent-chocolate-cake.png',
        '{}',
        'weight',
        '[{"weight": "0.5 Kg", "price": "499", "stock": "25", "isActive": true}]',
        '[{"quantity": "1 piece", "price": "499", "stock": "25", "isActive": true}]',
        350,
        500,
        5.0,
        20.0,
        40.0,
        30.0,
        2.0,
        100,
        'both',
        false,
        false,
        false,
        false,
        '{"Rich Flavor", "Moist Texture"}',
        '{"Flour", "Sugar", "Cocoa", "Eggs", "Butter"}',
        true
    );
-- Insert Red Velvet Cupcake
INSERT INTO products (
        name,
        short_description,
        long_description,
        category_id,
        is_veg,
        has_offer,
        offer_percentage,
        offer_up_to_price,
        banner_image,
        additional_images,
        selling_type,
        weight_options,
        piece_options,
        calories,
        net_weight,
        protein,
        fats,
        carbs,
        sugars,
        fiber,
        sodium,
        delivery_option,
        add_text_on_cake,
        add_candles,
        add_knife,
        add_message_card,
        highlights,
        ingredients,
        is_active
    )
VALUES (
        'Red Velvet Cupcake',
        'Classic red velvet cupcake with cream cheese frosting.',
        'A delightful red velvet cupcake, topped with tangy cream cheese frosting. A perfect individual treat.',
        cupcakes_id,
        true,
        true,
        10,
        60,
        '/red-velvet-cheesecake.png',
        '{}',
        'piece',
        '[]',
        '[{"quantity": "1 piece", "price": "199", "stock": "5", "isActive": true}]',
        250,
        100,
        3.0,
        15.0,
        25.0,
        20.0,
        1.0,
        80,
        'same-day',
        false,
        true,
        false,
        true,
        '{"Vibrant Color", "Cream Cheese Frosting"}',
        '{"Flour", "Sugar", "Cocoa", "Buttermilk", "Cream Cheese"}',
        true
    );
-- Insert Oatmeal Cookie
INSERT INTO products (
        name,
        short_description,
        long_description,
        category_id,
        is_veg,
        has_offer,
        offer_percentage,
        offer_up_to_price,
        banner_image,
        additional_images,
        selling_type,
        weight_options,
        piece_options,
        calories,
        net_weight,
        protein,
        fats,
        carbs,
        sugars,
        fiber,
        sodium,
        delivery_option,
        add_text_on_cake,
        add_candles,
        add_knife,
        add_message_card,
        highlights,
        ingredients,
        is_active
    )
VALUES (
        'Oatmeal Cookie',
        'Chewy oatmeal cookies with raisins.',
        'Hearty and chewy oatmeal cookies packed with plump raisins. A classic comfort food.',
        cookies_id,
        true,
        false,
        NULL,
        0,
        '/classic-chocolate-chip-cookies.png',
        '{}',
        'piece',
        '[]',
        '[{"quantity": "1 piece", "price": "99", "stock": "0", "isActive": false}]',
        150,
        50,
        2.0,
        8.0,
        20.0,
        10.0,
        3.0,
        50,
        'both',
        false,
        false,
        false,
        false,
        '{"Chewy Texture", "Healthy Oats"}',
        '{"Oats", "Flour", "Brown Sugar", "Raisins", "Cinnamon"}',
        false
    );
-- Insert Classic Croissant
INSERT INTO products (
        name,
        short_description,
        long_description,
        category_id,
        is_veg,
        has_offer,
        offer_percentage,
        offer_up_to_price,
        banner_image,
        additional_images,
        selling_type,
        weight_options,
        piece_options,
        calories,
        net_weight,
        protein,
        fats,
        carbs,
        sugars,
        fiber,
        sodium,
        delivery_option,
        add_text_on_cake,
        add_candles,
        add_knife,
        add_message_card,
        highlights,
        ingredients,
        is_active
    )
VALUES (
        'Classic Croissant',
        'Buttery, flaky croissants baked fresh daily.',
        'Authentic French croissants, made with layers of buttery, flaky pastry. Perfect for breakfast or a light snack.',
        pastries_id,
        true,
        false,
        NULL,
        0,
        '/golden-butter-croissant.png',
        '{}',
        'piece',
        '[]',
        '[{"quantity": "1 piece", "price": "149", "stock": "18", "isActive": true}]',
        280,
        80,
        4.0,
        18.0,
        25.0,
        5.0,
        1.0,
        150,
        'same-day',
        false,
        false,
        false,
        false,
        '{"Flaky Layers", "Buttery Taste"}',
        '{"Flour", "Butter", "Milk", "Yeast", "Sugar"}',
        true
    );
-- Insert Strawberry Cheesecake
INSERT INTO products (
        name,
        short_description,
        long_description,
        category_id,
        is_veg,
        has_offer,
        offer_percentage,
        offer_up_to_price,
        banner_image,
        additional_images,
        selling_type,
        weight_options,
        piece_options,
        calories,
        net_weight,
        protein,
        fats,
        carbs,
        sugars,
        fiber,
        sodium,
        delivery_option,
        add_text_on_cake,
        add_candles,
        add_knife,
        add_message_card,
        highlights,
        ingredients,
        is_active
    )
VALUES (
        'Strawberry Cheesecake',
        'Creamy cheesecake topped with fresh strawberries.',
        'A luscious cheesecake with a rich, creamy texture and a vibrant topping of fresh strawberries.',
        cakes_id,
        true,
        true,
        5,
        100,
        '/classic-strawberry-cheesecake.png',
        '{}',
        'weight',
        '[{"weight": "1 Kg", "price": "599", "stock": "7", "isActive": true}]',
        '[]',
        400,
        1000,
        8.0,
        25.0,
        50.0,
        40.0,
        3.0,
        120,
        'both',
        true,
        true,
        true,
        true,
        '{"Creamy Texture", "Fresh Strawberries"}',
        '{"Cream Cheese", "Sugar", "Eggs", "Strawberries", "Graham Cracker Crust"}',
        true
    );
-- Insert Chocolate Chip Cookie
INSERT INTO products (
        name,
        short_description,
        long_description,
        category_id,
        is_veg,
        has_offer,
        offer_percentage,
        offer_up_to_price,
        banner_image,
        additional_images,
        selling_type,
        weight_options,
        piece_options,
        calories,
        net_weight,
        protein,
        fats,
        carbs,
        sugars,
        fiber,
        sodium,
        delivery_option,
        add_text_on_cake,
        add_candles,
        add_knife,
        add_message_card,
        highlights,
        ingredients,
        is_active
    )
VALUES (
        'Chocolate Chip Cookie',
        'Classic chocolate chip cookies with a soft center.',
        'Perfectly baked chocolate chip cookies with a soft, chewy center and crispy edges. Loaded with premium chocolate chips.',
        cookies_id,
        true,
        false,
        NULL,
        0,
        '/classic-chocolate-chip-cookies.png',
        '{}',
        'piece',
        '[]',
        '[{"quantity": "1 piece", "price": "79", "stock": "30", "isActive": true}]',
        180,
        60,
        2.5,
        9.0,
        22.0,
        12.0,
        1.5,
        85,
        'both',
        false,
        false,
        false,
        false,
        '{"Soft Center", "Crispy Edges"}',
        '{"Flour", "Butter", "Sugar", "Chocolate Chips", "Eggs"}',
        true
    );
-- Insert Blueberry Muffin
INSERT INTO products (
        name,
        short_description,
        long_description,
        category_id,
        is_veg,
        has_offer,
        offer_percentage,
        offer_up_to_price,
        banner_image,
        additional_images,
        selling_type,
        weight_options,
        piece_options,
        calories,
        net_weight,
        protein,
        fats,
        carbs,
        sugars,
        fiber,
        sodium,
        delivery_option,
        add_text_on_cake,
        add_candles,
        add_knife,
        add_message_card,
        highlights,
        ingredients,
        is_active
    )
VALUES (
        'Blueberry Muffin',
        'Moist blueberry muffins with fresh berries.',
        'Deliciously moist muffins bursting with fresh blueberries. Perfect for breakfast or a sweet snack.',
        breads_id,
        true,
        false,
        NULL,
        0,
        '/blueberry-muffin.jpg',
        '{}',
        'piece',
        '[]',
        '[{"quantity": "1 piece", "price": "129", "stock": "20", "isActive": true}]',
        220,
        90,
        4.0,
        8.0,
        35.0,
        18.0,
        2.0,
        95,
        'same-day',
        false,
        false,
        false,
        false,
        '{"Fresh Blueberries", "Moist Texture"}',
        '{"Flour", "Sugar", "Blueberries", "Eggs", "Milk"}',
        true
    );
RAISE NOTICE 'Sample products inserted successfully!';
END $$;